const eventSchemaDefinition = {
  id: { type: String, required: true, unique: true },
  tenantId: { type: String, required: true },
  attachments: { type: Array, default: [] },
  attendees: {
    publicEvent: { type: Boolean, default: true },
    needsRegistration: { type: Boolean, default: false },
    free: { type: Boolean, default: false },
    maxAttendees: { type: Number, default: null },
    priceCategories: { type: Array, default: [] },
  },
  eventAddress: {
    street: { type: String, default: "" },
    houseNumber: { type: String, default: "" },
    additional: { type: String, default: "" },
    city: { type: String, default: "" },
    zip: { type: String, default: "" },
  },
  eventLocation: {
    name: { type: String, default: "" },
    phoneNumber: { type: String, default: "" },
    emailAddress: { type: String, default: "" },
    select: { type: String, default: null },
    room: { type: String, default: null },
    url: { type: String, default: "" },
  },
  eventOrganizer: {
    name: { type: String, default: "" },
    addContactPerson: { type: Boolean, default: true },
    contactPersonName: { type: String, default: "" },
    contactPersonPhoneNumber: { type: String, default: "" },
    contactPersonEmailAddress: { type: String, default: "" },
    contactPersonImage: { type: String, default: "" },
    speakers: { type: Array, default: [] },
  },
  format: { type: Number, default: 0 },
  images: { type: Array, default: [] },
  information: {
    name: { type: String, default: "" },
    teaserText: { type: String, default: "" },
    description: { type: String, default: "" },
    teaserImage: { type: String, default: null },
    startDate: { type: String, default: null },
    startTime: { type: String, default: null },
    endDate: { type: String, default: null },
    endTime: { type: String, default: null },
    tags: { type: Array, default: [] },
    flags: { type: Array, default: [] },
  },
  isPublic: { type: Boolean, default: false },
  schedules: { type: Array, default: [] },
  ownerUserId: { type: String, default: "" },
};

module.exports = {
  eventSchemaDefinition,
};
