const roleSchemaDefinition = {
  id: { type: String, required: true },
  name: { type: String, required: true },
  tenantId: { type: String, required: true },
  adminInterfaces: {
    type: [String],
    enum: [
      "locations",
      "users",
      "roles",
      "bookings",
      "coupons",
      "rooms",
      "resources",
      "tickets",
      "events",
    ],
    default: [],
  },
  manageUsers: {
    create: { type: Boolean, default: false },
    readAny: { type: Boolean, default: false },
    readOwn: { type: Boolean, default: false },
    updateAny: { type: Boolean, default: false },
    updateOwn: { type: Boolean, default: false },
    deleteAny: { type: Boolean, default: false },
    deleteOwn: { type: Boolean, default: false },
  },
  manageBookables: {
    create: { type: Boolean, default: false },
    readAny: { type: Boolean, default: false },
    readOwn: { type: Boolean, default: false },
    updateAny: { type: Boolean, default: false },
    updateOwn: { type: Boolean, default: false },
    deleteAny: { type: Boolean, default: false },
    deleteOwn: { type: Boolean, default: false },
  },
  manageBookings: {
    create: { type: Boolean, default: false },
    readAny: { type: Boolean, default: false },
    readOwn: { type: Boolean, default: false },
    updateAny: { type: Boolean, default: false },
    updateOwn: { type: Boolean, default: false },
    deleteAny: { type: Boolean, default: false },
    deleteOwn: { type: Boolean, default: false },
  },
  manageCoupons: {
    create: { type: Boolean, default: false },
    readAny: { type: Boolean, default: false },
    readOwn: { type: Boolean, default: false },
    updateAny: { type: Boolean, default: false },
    updateOwn: { type: Boolean, default: false },
    deleteAny: { type: Boolean, default: false },
    deleteOwn: { type: Boolean, default: false },
  },
  manageRoles: {
    create: { type: Boolean, default: false },
    readAny: { type: Boolean, default: false },
    readOwn: { type: Boolean, default: false },
    updateAny: { type: Boolean, default: false },
    updateOwn: { type: Boolean, default: false },
    deleteAny: { type: Boolean, default: false },
    deleteOwn: { type: Boolean, default: false },
  },
  assignedUserId: { type: String, default: null },
  freeBookings: { type: Boolean, default: false },
};

module.exports = {
  roleSchemaDefinition,
};
