const tenantSchemaDefinition = {
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  contactName: { type: String, default: "" },
  location: { type: String, default: "" },
  mail: { type: String, default: "" },
  phone: { type: String, default: "" },
  website: { type: String, default: "" },
  bookableDetailLink: { type: String, default: "" },
  eventDetailLink: { type: String, default: "" },
  genericMailTemplate: { type: String, default: "" },
  useInstanceMail: { type: Boolean, default: true },
  noreplyMail: { type: String, default: "" },
  noreplyDisplayName: { type: String, default: "" },
  noreplyHost: { type: String, default: "" },
  noreplyPort: { type: Number, default: "" },
  noreplyUser: { type: String, default: "" },
  noreplyPassword: { type: Object, default: null },
  noreplyStarttls: { type: Boolean, default: false },
  noreplyUseGraphApi: { type: Boolean, default: false },
  noreplyGraphTenantId: { type: String, default: "" },
  noreplyGraphClientId: { type: String, default: "" },
  noreplyGraphClientSecret: { type: Object, default: null },
  receiptTemplate: { type: String, default: "" },
  receiptNumberPrefix: { type: String, default: "" },
  receiptCount: { type: Object, default: {} },
  invoiceTemplate: { type: String, default: "" },
  invoiceNumberPrefix: { type: String, default: "" },
  invoiceCount: { type: Object, default: {} },
  paymentPurposeSuffix: { type: String, default: "" },
  applications: { type: Array, default: [] },
  maxBookingAdvanceInMonths: { type: Number, default: null },
  defaultEventCreationMode: { type: String, default: "" },
  enablePublicStatusView: { type: Boolean, default: false },
  ownerUserIds: { type: Array, default: [] },
  users: [
    {
      userId: { type: String, required: true },
      roles: { type: [String], default: [] },
    },
  ],
};

module.exports = tenantSchemaDefinition;
